name: recommendation-system
services:
  admin:
    build:
      context: https://github.com/ZPI-Recommendation-System/Recommendation-admin.git
      args:
        - REACT_APP_API_URL=$REACT_APP_API_URL
        - PUBLIC_URL=$PUBLIC_URL
    networks:
      - frontend
    restart: always
    hostname: admin
    healthcheck:
      test: "exit 0"
    depends_on:
      backend:
        condition: service_healthy

  frontend:
    build: 
      context: https://github.com/ZPI-Recommendation-System/Recommendation-Frontend.git
      args:
        - REACT_APP_API_URL=$REACT_APP_API_URL
    networks:
      - frontend
    restart: always
    hostname: frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: "exit 0"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: https://github.com/ZPI-Recommendation-System/Recommendation-Backend.git
    env_file:
      - config/.backend-env
    networks:
      - backend
      - frontend
    restart: always
    hostname: backend
    healthcheck:
      test: "exit 0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      scraper:
        condition: service_healthy

  scraper:
    build: https://github.com/ZPI-Recommendation-System/Scapper-System.git
    env_file:
      - config/.scraper-env
    networks:
      - backend
    volumes:
      - ./resources/offers.csv:/resources/prices.csv
    healthcheck:
      test: "exit 0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: scraper

  db:
    image: postgres
    volumes:
      - ./config/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    restart: always
    hostname: db
    networks:
      - backend
    env_file:
      - config/.db-env
    ports:
      - '5532:5432'
    healthcheck:
      test: "exit 0"

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    hostname: nginx_main
    networks:
      - frontend
      - backend
    ports:
      - '80:80'
      - '8080:8080'
    depends_on:
        frontend:
          condition: service_healthy
        admin:
          condition: service_healthy

networks:
  backend: {}
  frontend: {}
